format_version: 3
pipelines:
  Gambero1:
    group: Gambero
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    environment_variables:
      DOCKER_CONTENT_TRUST: '1'
    materials:
      git:
        git: https://github.com/gambe-ro/lobsters
        shallow_clone: false
        auto_update: true
        branch: master
        destination: gambero
    stages:
    - Deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          docker-compose_restart:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - cp -v /vagrant/app.env .env && script/docker-restart.sh -d
                command: bash
                working_directory: gambero
                run_if: passed
    - Healthcheck:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          HTTPRequest:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -fLI
                - --retry
                - '6'
                - https://gambe.ro
                command: curl
                run_if: passed
